version: '3.7'

services:

  server1:
    build:
      context: .
      dockerfile: DockerfileServer
    hostname: server1
    environment:
      SERVER_ID: "0"
    env_file:
      - .env
    ports:
      - "8085:8085"
    networks:
      - my_network

  server2:
    build:
      context: .
      dockerfile: DockerfileServer
    hostname: server2
    environment:
      SERVER_ID: "1"
    env_file:
      - .env
    ports:
      - "8086:8086"
    networks:
      - my_network

  server3:
    build:
      context: .
      dockerfile: DockerfileServer
    hostname: server3
    environment:
      SERVER_ID: "2"
    env_file:
      - .env
    ports:
      - "8087:8087"
    networks:
      - my_network


  client:
    build:
      context: .
      dockerfile: DockerfileClient
    hostname: client
    tty: true
    stdin_open: true
    env_file:
      - .env
    depends_on:
      - server1
      - server2
      - server3
    networks:
      - my_network
    ports:
      - "8081:8081"

networks:
  my_network:
    driver: bridge